routes/web.php
<?php

use App\Http\Controllers\Account\SettingsController;
use App\Http\Controllers\ActivityLogController;
use App\Http\Controllers\Approval\ApprovalController;
use App\Http\Controllers\Approval\StatusController;
use App\Http\Controllers\Auth\SocialiteLoginController;
use App\Http\Controllers\CityProvince\CityProvinceController;
use App\Http\Controllers\Documentation\LayoutBuilderController;
use App\Http\Controllers\Documentation\ReferencesController;
use App\Http\Controllers\ElectronicReport\FinishedReprotController;
use App\Http\Controllers\ElectronicReport\PenugasanReportController;
use App\Http\Controllers\EngineeringDatabase\Port\PortDrawingController;
use App\Http\Controllers\EngineeringDatabase\Port\TechnicalQualityStandardController;
use App\Http\Controllers\EngineeringDatabase\Port\FacilityStandardController;
use App\Http\Controllers\EngineeringDatabase\Port\PortSpecificationController;
use App\Http\Controllers\EngineeringDatabase\Port\DocumentOfQualityController;
use App\Http\Controllers\EngineeringDatabase\Fleet\EquipmentBoardController;
use App\Http\Controllers\Logs\AuditLogsController;
use App\Http\Controllers\Logs\SystemLogsController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Port\RegionController;
use App\Http\Controllers\Port\BranchController;
use App\Http\Controllers\Port\BranchSubController;
use App\Http\Controllers\Port\PortController;
use App\Http\Controllers\Port\DockController;
use App\Http\Controllers\Port\Form\PortFormController;
use App\Http\Controllers\Port\Form\PortFormGroupController;
use App\Http\Controllers\Port\Form\PortFormGroupItemController;

use App\Http\Controllers\Fleet\RegionController as FleetRegion;
use App\Http\Controllers\Fleet\BranchController as FleetBranch;
use App\Http\Controllers\Fleet\FleetController;
use App\Http\Controllers\Fleet\RouteController;
use App\Http\Controllers\Fleet\SubBranchController;
use App\Http\Controllers\Fleet\TypeOfTrackController;
use App\Http\Controllers\Fleet\TrackController;
use App\Http\Controllers\Fleet\Form\FleetFormController;
use App\Http\Controllers\Fleet\Form\FleetFormGroupController;
use App\Http\Controllers\Fleet\Form\FleetFormGroupItemController;


use App\Http\Controllers\ElectronicReport\ProgressReportController;
use App\Http\Controllers\EngineeringDatabase\Fleet\EngineeringDocumentController;
use App\Http\Controllers\EngineeringDatabase\Fleet\FleetFacilityStandardController;
use App\Http\Controllers\EngineeringDatabase\Fleet\FleetTechnicalStandardController;
use App\Http\Controllers\EngineeringDatabase\Fleet\ManualBookController;
use App\Http\Controllers\EngineeringDatabase\Fleet\ShipDocumentController;
use App\Http\Controllers\ERCM\Fleet\FleetERCMController;
use App\Http\Controllers\ERCM\Port\PortERCMController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ProjectMonitoring\Fleet\BasicDataController;

use App\Http\Controllers\ProjectMonitoring\Fleet\DocumentController as FleetDocumentController;
use App\Http\Controllers\ProjectMonitoring\Fleet\ProjectController as FleetProjectController;
use App\Http\Controllers\ProjectMonitoring\Fleet\ProgressController as FleetProgressController;
use App\Http\Controllers\ProjectMonitoring\Port\BasicDataController as PortBasicDataController;
use App\Http\Controllers\ProjectMonitoring\Fleet\RecomendationController as FleetRecomendationController;
use App\Http\Controllers\ProjectMonitoring\Fleet\SummaryController as FleetSummaryController;
use App\Http\Controllers\ProjectMonitoring\Fleet\QualityController as FleetQualityController;
use App\Http\Controllers\ProjectMonitoring\Fleet\CompletionController as FleetCompletionController;

use App\Http\Controllers\ProjectMonitoring\Port\DocumentController as PortDocumentController;
use App\Http\Controllers\ProjectMonitoring\Port\ProjectController as PortProjectController;
use App\Http\Controllers\ProjectMonitoring\Port\ProgressController as PortProgressController;
use App\Http\Controllers\ProjectMonitoring\Port\RecomendationController as PortRecomendationController;
use App\Http\Controllers\ProjectMonitoring\Port\SummaryController as PortSummaryController;
use App\Http\Controllers\ProjectMonitoring\Port\CompletionController as PortCompletionController;
use App\Http\Controllers\ProjectMonitoring\Port\QualityController as PortQualityController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    dd("hei");
    return redirect('index');
});

$menu = theme()->getMenu();
array_walk($menu, function ($val) {
    if (isset($val['path'])) {
        $route = Route::get($val['path'], [PagesController::class, 'index']);

        // Exclude documentation from auth middleware
        if (!Str::contains($val['path'], 'documentation')) {
            $route->middleware('auth');
        }

        // Custom page demo for 500 server error
        if (Str::contains($val['path'], 'error-500')) {
            Route::get($val['path'], function () {
                abort(500, 'Something went wrong! Please try again later.');
            });
        }
    }
});

// Documentations pages
Route::prefix('documentation')->group(function () {
    Route::get('getting-started/references', [ReferencesController::class, 'index']);
    Route::get('getting-started/changelog', [PagesController::class, 'index']);
    Route::resource('layout-builder', LayoutBuilderController::class)->only(['store']);
});

Route::middleware('auth')->group(function () {
    // Account pages
    Route::prefix('account')->group(function () {
        Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
        Route::put('settings', [SettingsController::class, 'update'])->name('settings.update');
        Route::put('settings/email', [SettingsController::class, 'changeEmail'])->name('settings.changeEmail');
        Route::put('settings/password', [SettingsController::class, 'changePassword'])->name('settings.changePassword');
    });

    // Logs pages
    Route::prefix('log')->name('log.')->group(function () {
        Route::resource('system', SystemLogsController::class)->only(['index', 'destroy']);
        Route::resource('audit', AuditLogsController::class)->only(['index', 'destroy']);
    });

    Route::resource('/users', UserController::class)->except(['create', 'edit', 'update']);
    Route::post('users/{user}/update', [UserController::class, 'update'])->name('users.update');
    Route::post('users/{user}/update-status', [UserController::class, 'updateStatus'])->name('users.updateStatus');
    Route::resource('/roles', RoleController::class)->except(['create', 'edit', 'update']);
    Route::post('roles/{role}/update', [RoleController::class, 'update'])->name('roles.update');
    Route::resource('/permissions', PermissionController::class)->except(['create', 'edit', 'update']);
    Route::post('permissions/{permission}/update', [PermissionController::class, 'update'])->name('permissions.update');

    //Notification
    Route::resource('/notifications', NotificationController::class)
        ->only(['index', 'update']);

    // Port
    Route::prefix('port')->name('port.')->group(function () {
        // Region
        Route::get('region', [RegionController::class, 'index'])->name('region.index');
        Route::post('region/store', [RegionController::class, 'store'])->name('region.store');
        Route::get('region/{region}', [RegionController::class, 'show'])->name('region.show');
        Route::post('region/{region}/update', [RegionController::class, 'update'])->name('region.update');
        Route::delete('region/{region}/delete', [RegionController::class, 'destroy'])->name('region.destroy');

        // Branch
        Route::get('branch', [BranchController::class, 'index'])->name('branch.index');
        Route::post('branch/store', [BranchController::class, 'store'])->name('branch.store');
        Route::get('branch/{branch}', [BranchController::class, 'show'])->name('branch.show');
        Route::post('branch/{branch}/update', [BranchController::class, 'update'])->name('branch.update');
        Route::delete('branch/{branch}/delete', [BranchController::class, 'destroy'])->name('branch.destroy');

        // Sub Branch
        Route::get('sub_branch', [BranchSubController::class, 'index'])->name('sub_branch.index');
        Route::post('sub_branch/store', [BranchSubController::class, 'store'])->name('sub_branch.store');
        Route::get('sub_branch/{branch_sub}', [BranchSubController::class, 'show'])->name('sub_branch.show');
        Route::post('sub_branch/{branch_sub}/update', [BranchSubController::class, 'update'])->name('sub_branch.update');
        Route::delete('sub_branch/{branch_sub}/delete', [BranchSubController::class, 'destroy'])->name('sub_branch.destroy');
        Route::get('ajax_get_city', [BranchSubController::class, 'ajax_get_city'])->name('ajax_get_city');

        // Port
        Route::get('port', [PortController::class, 'index'])->name('port.index');
        Route::post('port/store', [PortController::class, 'store'])->name('port.store');
        Route::get('port/{port}', [PortController::class, 'show'])->name('port.show');
        Route::post('port/{port}/update', [PortController::class, 'update'])->name('port.update');
        Route::delete('port/{port}/delete', [PortController::class, 'destroy'])->name('port.destroy');
        Route::get('ajax_get_branch', [PortController::class, 'ajax_get_branch'])->name('ajax_get_branch');

        // Dock

app/Models/ERCM/Port.php
<?php

namespace App\Models\ERCM;

use App\Models\Port\Port as MstPort;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Enums\ERCMStatusEnum;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Port extends Model
{
    use HasFactory, LogsActivity;

    protected $table = 'ercm_pelabuhans';

    protected $fillable = [
        'pelabuhan_id',
        'status',
        'updated_by'
    ];

    protected $moduleName = 'ERCM Port';

    protected $casts = [
        'status' => ERCMStatusEnum::class
    ];

    public function port(){
        return $this->belongsTo(MstPort::class, 'pelabuhan_id', 'id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->setDescriptionForEvent(fn(string $eventName) => $this->moduleName. ' has been '. $eventName)
            ->logAll()
            ->logOnlyDirty();
    }
}

app/Models/EngineeringDatabase/Port/DocumentOfQuality.php
<?php

namespace App\Models\EngineeringDatabase\Port;

use App\Models\EngineeringDatabase\Approval;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class DocumentOfQuality extends Model
{
    use HasFactory, LogsActivity;

    protected $table = 'ed_document_of_quality';

    protected $guarded = [
        'id'
    ];

    protected $moduleName = 'Document of Quality';

    public function approval()
    {
        return $this->belongsTo(Approval::class, 'approval_id', 'id');
    }

    public function documents()
    {
        return $this->hasMany(DocumentOfQualityFile::class, 'document_of_quality_id', 'id');
    }

    public function scopeSelectApproval($query)
    {
        return $query->selectRaw('approval_id, dermaga_id AS item')->whereNotNull('approval_id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->setDescriptionForEvent(fn(string $eventName) => $this->moduleName. ' has been '. $eventName)
            ->logAll()
            ->logOnlyDirty();
    }
}

app/Models/EngineeringDatabase/Port/DocumentOfQualityFile.php
<?php

namespace App\Models\EngineeringDatabase\Port;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class DocumentOfQualityFile extends Model
{
    use HasFactory, LogsActivity;

    protected $table = 'ed_document_of_quality_file';

    protected $guarded = [
        'id'
    ];

    protected $moduleName = 'Document of Quality File';

    public function documentOfQuality()
    {
        return $this->belongsTo(DocumentOfQuality::class, 'document_of_quality_id', 'id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->setDescriptionForEvent(fn(string $eventName) => $this->moduleName. ' has been '. $eventName)
            ->logAll()
            ->logOnlyDirty();
    }
}

app/Models/EngineeringDatabase/Port/FacilityStandard.php
<?php

namespace App\Models\EngineeringDatabase\Port;

use App\Models\EngineeringDatabase\Approval;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class FacilityStandard extends Model
{
    use HasFactory, LogsActivity;

    protected $table = 'ed_facility_standard';

    protected $guarded = [
        'id'
    ];

    protected $moduleName = 'Facility Standard';

    public function approval()
    {
        return $this->belongsTo(Approval::class, 'approval_id', 'id');
    }

    public function documents()
    {
        return $this->hasMany(FacilityStandardFile::class, 'facility_standard_id', 'id');
    }

    public function dokumen()
    {
        return $this->hasMany(FacilityStandardFile::class, 'facility_standard_id', 'id');
    }

    public function scopeSelectApproval($query)
    {
        return $query->selectRaw('approval_id, nama_dokumen AS item')->whereNotNull('approval_id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->setDescriptionForEvent(fn(string $eventName) => $this->moduleName. ' has been '. $eventName)
            ->logAll()
            ->logOnlyDirty();
    }
}

app/Models/EngineeringDatabase/Port/FacilityStandardFile.php
<?php

namespace App\Models\EngineeringDatabase\Port;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class FacilityStandardFile extends Model
{
    use HasFactory, LogsActivity;

    protected $table = 'ed_facility_standard_file';

    protected $guarded = [
        'id'
    ];

    protected $moduleName = 'Facility Standard File';

    public function facilityStandard()
    {
        return $this->belongsTo(FacilityStandard::class, 'facility_standard_id', 'id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->setDescriptionForEvent(fn(string $eventName) => $this->moduleName. ' has been '. $eventName)
            ->logAll()
            ->logOnlyDirty();
    }
}

app/Models/EngineeringDatabase/Port/PortDrawing.php
<?php

namespace App\Models\EngineeringDatabase\Port;

use App\Models\EngineeringDatabase\Approval;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class PortDrawing extends Model
{
    use HasFactory, LogsActivity;

    protected $table = 'ed_port_drawing';

    protected $guarded = [
        'id'
    ];

    protected $moduleName = 'Port Drawing';

    public function approval()
    {
        return $this->belongsTo(Approval::class, 'approval_id', 'id');
    }

    public function documents()
    {
        return $this->hasMany(PortDrawingFile::class, 'port_drawing_id', 'id');
    }

    public function dokumen()
    {
        return $this->hasMany(PortDrawingFile::class, 'port_drawing_id', 'id');
    }

    public function scopeSelectApproval($query)
    {
        return $query->selectRaw('approval_id, dermaga_id AS item')->whereNotNull('approval_id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->setDescriptionForEvent(fn(string $eventName) => $this->moduleName. ' has been '. $eventName)
            ->logAll()
            ->logOnlyDirty();
    }
}

app/Models/EngineeringDatabase/Port/PortDrawingFile.php
<?php

namespace App\Models\EngineeringDatabase\Port;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class PortDrawingFile extends Model
{
    use HasFactory, LogsActivity;

    protected $table = 'ed_port_drawing_file';

    protected $guarded = [
        'id'
    ];

    protected $moduleName = 'Port Drawing File';

    public function portDrawing()
    {
        return $this->belongsTo(PortDrawing::class, 'port_drawing_id', 'id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->setDescriptionForEvent(fn(string $eventName) => $this->moduleName. ' has been '. $eventName)
            ->logAll()
            ->logOnlyDirty();
    }
}

resources/views/pages/port/region/index.blade.php
@extends('layout.demo1.master')

@section('styles')
<link rel="stylesheet" href="{{ asset('demo1/plugins/custom/datatables/datatables.bundle.css') }}" type="text/css">
@endsection

@section('content-module')
<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
	<div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
        <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
            <h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">{{ __('Data Region') }}</h1>
            <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                <li class="breadcrumb-item text-muted">
                    <a href="/" class="text-muted text-hover-primary">{{ __('Beranda') }}</a>
                </li>
                <li class="breadcrumb-item">
                    <span class="bullet bg-gray-400 w-5px h-2px"></span>
                </li>
                <li class="breadcrumb-item text-muted">{{ __('Region') }}</li>
            </ul>
        </div>
	</div>
</div>

<div id="kt_app_content" class="app-content flex-column-fluid">
	<div id="kt_app_content_container" class="app-container container-fluid">
        <div class="card shadow-sm">
            <div class="card-header">
                <h3 class="card-title">{{ __('Data Region') }}</h3>
                <div class="card-toolbar">
                    <button type="button"
                    id="btn_create_region_modal"
                    class="btn btn-sm btn-light"
                    data-bs-toggle="modal"
                    data-bs-target="#create_region_modal">
                        <i class="fa fa-plus"></i>
                        {{ __('Tambah') }}
                    </button>
                    <button type="button"
                    id="btn_edit_region_modal"
                    data-bs-toggle="modal"
                    data-bs-target="#edit_region_modal"
                    hidden>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="region_table">
                        <thead>
                            <tr class="fw-bold fs-6 text-gray-800">
                                <th>{{ __('No') }}</th>
                                <th width="70%">{{ __('Region') }}</th>
                                <th>{{ __('Aksi') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>
@endsection

@include('pages.port.region.modals.create')
@include('pages.port.region.modals.edit')

@section('scripts')
<script src="{{ asset('demo1/plugins/custom/datatables/datatables.bundle.js') }}" type="text/javascript"></script>
<script>
    function checkSession() {
        if ('{{ Session::has('success') }}') {
            Swal.fire({
                text: '{{ Session::get('success') }}',
                icon: "success"
            });
        }

        if ('{{ Session::has('failed') }}') {
            Swal.fire({
                text: '{{ Session::get('failed') }}',
                icon: "error"
            });
        }
    }

    if ($('.modal .is-invalid').length > 0) {
        var action = "{{ old('action') }}";
        $('#btn_' + action + '_region_modal').trigger('click');
    }

    $(document).ready(function () {
        checkSession();

        var table = $('#region_table').DataTable({
                proccesing: true,
                serverSide: true,
                order: [],
                ajax: {
                    url: "{{ route('port.region.index') }}"
                },
                columns: [
                    {
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false,
                    },
                    {
                        data: 'nama',
                        name: 'nama'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ],
            });

        $(document).on('click', '.btn-edit-region', function () {
            var url = `{{ route('port.region.show', ':region') }}`;
            url = url.replace(':region', $(this).data('id'));

            $.ajax({
                url: url,
                type: "GET",
                data:{
                    "_token": "{{ csrf_token() }}",
                },
                success: function (data) {

                    var action = `{{ route('port.region.update', ':region') }}`;
                    action = action.replace(':region', data.id);

                    $('#edit_region_modal form').prop('action', action);

                    $('#edit_region_modal input[name="nama"]').val(data.nama);

                }
            });
        });

        $(document).on('click', '.btn-delete-region', function () {
            var url = `{{ route('port.region.destroy', ':region') }}`;
            url = url.replace(':region', $(this).data('id'));

            Swal.fire({
                title: "{{ __('Apakah kamu yakin?') }}",
                text: "{{ __('Data akan terhapus secara permanen!') }}",
                icon: "warning",
                showCancelButton: true,
                confirmButtonText: "{{ __('Ya') }}",
                cancelButtonText: "{{ __('Batal') }}",
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: url,
                        type: "DELETE",
                        data:{
                            "_token": "{{ csrf_token() }}",
                        },
                        success: function () {
                            location.reload();
                        }
                    });
                }
            });
        });


        $(document).on('hidden.bs.modal', '.modal', function () {
            $('.is-invalid').each(function (index, element) {
                $(this).removeClass('is-invalid');
            });
        });

        $(document).on('click', '#btn_create_region_modal', function () {
            $('input').not('input[type="hidden"]').each(function (index, element) {
                $(this).val('');
            });
        });
    })
</script>
@endsection